spring:
  application:
    name: api-gateway
  profiles:    active: development
    include: development
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB
      
management:  endpoints:    web:      exposure:        include: '*'

server:  port: 8001
  
logging:  level:    web: DEBUG
 
#Disable Eureka client temparatly . it work inside application.yml only, not bootstrap.yml
eureka:
  client:
    enabled: false
---
spring:  profiles: development

# with out Netflex Eureka Server
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 30s
      routes:
      - id: path_route
        uri: http://localhost:9001/
        predicates:
        - Path=/user-gateway/**
        
      - id: path_route
        uri: http://localhost:8080/
        predicates:
        - Path=/login-gateway/**
        

# with Netflex Eureka Server
#  cloud:
#    gateway:
#      #httpclient:#        #connect-timeout: 3
#        #response-timeout: 3
#      routes:
#      - id: user-service
#        uri: lb://user-service
#        predicates:
#        - Path=/user-gateway/**
#      - id: login-service
#        uri: lb://login-service
#        predicates:
#        - Path=/login-gateway/**      